[package]
name = "cy8c624abzi-d44"
version = "0.1.0"
authors = ["Jack (Butch) Griffin <butchg@comcast.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
