#[doc = "Reader of register AUTO_CMD_STAT_R"]
pub type R = crate::R<u16, super::AUTO_CMD_STAT_R>;
#[doc = "Reader of field `AUTO_CMD12_NOT_EXEC`"]
pub type AUTO_CMD12_NOT_EXEC_R = crate::R<bool, bool>;
#[doc = "Reader of field `AUTO_CMD_TOUT_ERR`"]
pub type AUTO_CMD_TOUT_ERR_R = crate::R<bool, bool>;
#[doc = "Reader of field `AUTO_CMD_CRC_ERR`"]
pub type AUTO_CMD_CRC_ERR_R = crate::R<bool, bool>;
#[doc = "Reader of field `AUTO_CMD_EBIT_ERR`"]
pub type AUTO_CMD_EBIT_ERR_R = crate::R<bool, bool>;
#[doc = "Reader of field `AUTO_CMD_IDX_ERR`"]
pub type AUTO_CMD_IDX_ERR_R = crate::R<bool, bool>;
#[doc = "Reader of field `AUTO_CMD_RESP_ERR`"]
pub type AUTO_CMD_RESP_ERR_R = crate::R<bool, bool>;
#[doc = "Reader of field `CMD_NOT_ISSUED_AUTO_CMD12`"]
pub type CMD_NOT_ISSUED_AUTO_CMD12_R = crate::R<bool, bool>;
impl R {
    #[doc = "Bit 0 - Auto CMD12 Not Executed If multiple memory block data transfer is not started due to a command error, this bit is not set because it is not necessary to issue an Auto CMD12. Setting this bit to 1 means that the Host Controller cannot issue Auto CMD12 to stop multiple memory block data transfer, due to some error. If this bit is set to 1, error status bits (D04-D01) is meaningless. This bit is set to 0 when Auto CMD Error is generated by Auto CMD23. Values: - 0x1 (TRUE): Not Executed - 0x0 (FALSE): Executed"]
    #[inline(always)]
    pub fn auto_cmd12_not_exec(&self) -> AUTO_CMD12_NOT_EXEC_R {
        AUTO_CMD12_NOT_EXEC_R::new((self.bits & 0x01) != 0)
    }
    #[doc = "Bit 1 - Auto CMD Timeout Error This bit is set if no response is returned with 64 SDCLK cycles from the end bit of the command. If this bit is set to 1, error status bits (D04-D01) are meaningless. Values: - 0x1 (TRUE): Time out - 0x0 (FALSE): No Error"]
    #[inline(always)]
    pub fn auto_cmd_tout_err(&self) -> AUTO_CMD_TOUT_ERR_R {
        AUTO_CMD_TOUT_ERR_R::new(((self.bits >> 1) & 0x01) != 0)
    }
    #[doc = "Bit 2 - Auto CMD CRC Error This bit is set when detecting a CRC error in the command response. Values: - 0x1 (TRUE): CRC Error Generated - 0x0 (FALSE): No Error"]
    #[inline(always)]
    pub fn auto_cmd_crc_err(&self) -> AUTO_CMD_CRC_ERR_R {
        AUTO_CMD_CRC_ERR_R::new(((self.bits >> 2) & 0x01) != 0)
    }
    #[doc = "Bit 3 - Auto CMD End Bit Error This bit is set when detecting that the end bit of command response is 0. Values: - 0x1 (TRUE): End Bit Error Generated - 0x0 (FALSE): No Error"]
    #[inline(always)]
    pub fn auto_cmd_ebit_err(&self) -> AUTO_CMD_EBIT_ERR_R {
        AUTO_CMD_EBIT_ERR_R::new(((self.bits >> 3) & 0x01) != 0)
    }
    #[doc = "Bit 4 - Auto CMD Index Error This bit is set if the command index error occurs in response to a command. Values: - 0x1 (TRUE): Error - 0x0 (FALSE): No Error"]
    #[inline(always)]
    pub fn auto_cmd_idx_err(&self) -> AUTO_CMD_IDX_ERR_R {
        AUTO_CMD_IDX_ERR_R::new(((self.bits >> 4) & 0x01) != 0)
    }
    #[doc = "Bit 5 - Auto CMD Response Error This bit is set when Response Error Check Enable in the Transfer Mode register is set to 1 and an error is detected in R1 response of either Auto CMD12 or CMD13. This status is ignored if any bit between D00 to D04 is set to 1. Values: - 0x1 (TRUE): Error - 0x0 (FALSE): No Error"]
    #[inline(always)]
    pub fn auto_cmd_resp_err(&self) -> AUTO_CMD_RESP_ERR_R {
        AUTO_CMD_RESP_ERR_R::new(((self.bits >> 5) & 0x01) != 0)
    }
    #[doc = "Bit 7 - Command Not Issued By Auto CMD12 Error If this bit is set to 1, CMD_wo_DAT is not executed due to an Auto CMD12 Error (D04-D01) in this register. This bit is set to 0 when Auto CMD Error is generated by Auto CMD23. Values: - 0x1 (TRUE): Not Issued - 0x0 (FALSE): No Error"]
    #[inline(always)]
    pub fn cmd_not_issued_auto_cmd12(&self) -> CMD_NOT_ISSUED_AUTO_CMD12_R {
        CMD_NOT_ISSUED_AUTO_CMD12_R::new(((self.bits >> 7) & 0x01) != 0)
    }
}
