#[doc = "Reader of register CQCRDCT"]
pub type R = crate::R<u32, super::CQCRDCT>;
#[doc = "Reader of field `DCMD_RESP`"]
pub type DCMD_RESP_R = crate::R<u32, u32>;
impl R {
    #[doc = "Bits 0:31 - This register contains the response of the command generated by the last direct command (DCMD) task that was sent. Contents of this register are valid only after bit 31 of CQTDBR register is cleared by the controller."]
    #[inline(always)]
    pub fn dcmd_resp(&self) -> DCMD_RESP_R {
        DCMD_RESP_R::new((self.bits & 0xffff_ffff) as u32)
    }
}
