#!/bin/bash

TARGET=$1
SVDFILE=$2
PERIFILE=$3
CHIPTOOL=$4

echo "    TARGET is $TARGET"
echo "    SVDFILE is $SVDFILE"
echo "    PERIFILE is $PERIFILE"

readarray -t PERIPHERALS < $PERIFILE

for key in "${PERIPHERALS[@]}"
do
    PERIPHERAL=`echo $key | tr -d '\r'`
    echo -n "Cleaning peripheral $PERIPHERAL ... "
    cp $PERIPHERAL.rs $PERIPHERAL.orig
    sed '/no_std/d' $PERIPHERAL.rs > tmp
    sed -n '1,2p' tmp > $PERIPHERAL.rs 
    echo 'use core::prelude::v1::derive;' >> $PERIPHERAL.rs
    sed -e '1,2d' < tmp >> $PERIPHERAL.rs
    echo done
done
