#!/bin/bash

CHIPTOOL=../../../chiptool/target/debug/chiptool.exe

if [ ! -f chiptool/target/debug/chiptool.exe ];
then
    echo -n "Cloning 'chiptool' ..."
    git clone https://github.com/embassy-rs/chiptool.git >& /dev/null 2>&1
    echo done
    pushd chiptool
    git checkout staging
    echo -n "Building 'chiptool' ... "
    cargo build >& /dev/null 2>&1
    echo done
    popd
else
    echo "Chiptool already exists"
fi

rm -rf psoc6dev
if [ -d psoc6dev ]; then
    echo "Cannot remove psoc6dev directory. Aborting."
    exit 1
fi

mkdir -p psoc6dev/src
pushd psoc6dev >& /dev/null 2>&1
cp ../svd/common.rs src
cp -r ../svd/common src

cat > Cargo.toml << EOF
[package]
name = "psoc6dev"
description="PSoC 6 Cortex-M peripheral device definitions"
license="MIT"
version = "0.1.0"
readme = "README.md"
authors = ["Jack (Butch) Griffin <butchg@comcast.net>"]
edition = "2018"
keywords = ["cortex-m", "psoc", "no_std", "embedded"]
categories = ["embedded", "no-std"]

[features]
rt = ["cortex-m-rt/device"]

[dependencies]
cortex-m = "0.7.7"
cortex-m-rt = "0.7.3"
EOF

echo "#![allow(non_snake_case)]" > src/lib.rs
echo "pub mod common ;" >> src/lib.rs

for SVD in ../svd/*.svd
do
    SVDFILE="$(basename -- $SVD)"
    TARGETFILE="${SVDFILE%.*}"
    TARGET="${TARGETFILE/_/}"
    echo "pub mod $TARGET ;" >> src/lib.rs
    rm -rf src/$TARGET
    mkdir -p src/$TARGET
    pushd src/$TARGET >& /dev/null 2>&1
    echo "================================================================================"
    echo Processing SVD file $SVDFILE
    ../../../genrs $TARGET ../../../svd/$TARGETFILE.svd ../../../svd/$TARGET.peris $CHIPTOOL
    popd >& /dev/null 2>&1
    echo "================================================================================"
done

echo -n "Reformatting library source code ... "
cargo fmt
echo done

for SVD in ../svd/*.svd
do
    SVDFILE="$(basename -- $SVD)"
    TARGETFILE="${SVDFILE%.*}"
    TARGET="${TARGETFILE/_/}"
    pushd src/$TARGET >& /dev/null 2>&1
    echo "================================================================================"
    echo Cleaning  library $TARGET
    ../../../cleanrs $TARGET ../../../svd/$TARGETFILE.svd ../../../svd/$TARGET.peris $CHIPTOOL
    popd >& /dev/null 2>&1
    echo "================================================================================"
done

popd >& /dev/null 2>&1
