#!/bin/bash

TARGET=$1
SVDFILE=$2
PERIFILE=$3
CHIPTOOL=$4

echo "    TARGET is $TARGET"
echo "    SVDFILE is $SVDFILE"
echo "    PERIFILE is $PERIFILE"

readarray -t PERIPHERALS < $PERIFILE

mkdir -p yaml

for key in "${PERIPHERALS[@]}"
do
    PERIPHERAL=`echo $key | tr -d '\r'`
    echo -n "Processing peripheral $PERIPHERAL ... "
    echo "pub mod $PERIPHERAL;" >> mod.rs
    echo -n "Generating YAML ... "
    $CHIPTOOL extract-peripheral --svd $SVDFILE --peripheral $PERIPHERAL > yaml/$PERIPHERAL.yaml
    echo -n "Generating rust ... "
    $CHIPTOOL gen-block --input yaml/$PERIPHERAL.yaml --output $PERIPHERAL.rs
    echo done
done
