#!/bin/bash

CHIPTOOL=../../chiptool/target/debug/chiptool.exe


TARGET=$1
SVDFILE=$2
PERIFILE=$3

echo TARGET is $TARGET, SVDFILE is $SVDFILE, PERIFILE is $PERIFILE

readarray -t PERIPHERALS < $PERIFILE

mkdir -p yaml
mkdir -p src

for key in "${PERIPHERALS[@]}"
do
    PERIPHERAL=`echo $key | tr -d '\r'`
    echo -n "Processing peripheral $PERIPHERAL ... "
    echo "pub mod $PERIPHERAL;" >> src/mod.rs
    echo -n "Generating YAML ... "
    $CHIPTOOL extract-peripheral --svd $SVDFILE --peripheral $PERIPHERAL > yaml/$PERIPHERAL.yaml
    echo -n "Generating rust ... "
    $CHIPTOOL gen-block --input yaml/$PERIPHERAL.yaml --output src/$PERIPHERAL.rs
    echo done
done



